version: '3'

services:
  httpd:
    container_name: httpd-container
    image: satohjohn/kotlin-sample-httpd
    build: ./docker/httpd
    ports:
      - "80:80"
  tomcat:
    container_name: tomcat-container
    image: satohjohn/kotlin-sample-tomcat
    build: ./docker/tomcat
    volumes:
      - ./build/libs/app.war:/usr/local/tomcat/webapps/app.war
    expose:
      - "8009"
